server:
    port: ${PORT:8094}
    servlet:
        context-path: /parkTicketing


spring:
    config:
        additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

    rabbitmq:
        host: localhost
        port: 5672
        username: myuser
        password: mypassword
