### Get access token with normal user

POST http://localhost:8180/realms/techtopia/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id = techtopia-be &
client_secret = DfitZnoTBv2a6VQPCBnwBspWSZSSHN8N &
username = peter &
password = password &
grant_type = password &
scope = openid

> {%
	client.global.set("access_token", response.body.access_token);
%}


### buy a ticket valid for today
< {%
	request.variables.set("today", new Date().toISOString().slice(0, 10));
%}
POST {{baseURL}}/ticket/{{ticketUUID}}/valid-on/{{today}}
Authorization: Bearer {{access_token}}


### buy a ticket valid for a specific day
POST {{baseURL}}/ticket/{{nonValidTicketID}}/valid-on/{{date}}
Authorization: Bearer {{access_token}}


### visitor entering park
POST {{baseURL}}/visitor/enter/{{ticketUUID}}/gate/{{$uuid}}
Authorization: Bearer {{access_token}}


### visitor leaving park
POST {{baseURL}}/visitor/leave/{{ticketUUID}}/gate/{{$uuid}}
Authorization: Bearer {{access_token}}


### leaving park with LOST ticket
POST {{baseURL}}/visitor/leave/{{lostTicketID}}/gate/{{$uuid}}
Authorization: Bearer {{access_token}}


### enter park with not valid ticket
POST {{baseURL}}/visitor/enter/{{nonValidTicketID}}/gate/{{$uuid}}
Authorization: Bearer {{access_token}}


### enqueue on attraction
POST {{baseURL}}/attractions/{{attractionID}}/enqueue
Authorization: Bearer {{access_token}}


### dequeue on attraction
POST {{baseURL}}/attractions/{{attractionID}}/dequeue
Authorization: Bearer {{access_token}}


### forecast weather
GET {{baseURL}}/weather/{{date}}
Authorization: Bearer {{access_token}}


### forecast weather for today
< {%
	request.variables.set("today", new Date().toISOString().slice(0, 10));
%}
GET {{baseURL}}/weather/{{today}}
Authorization: Bearer {{access_token}}


### emptying cache for weather forecast
DELETE {{baseURL}}/cache/weather
Authorization: Bearer {{access_token}}


### forecast visitor count
GET {{baseURL}}/forecast/{{date}}
Authorization: Bearer {{access_token}}


### emptying cache for visitor forecast
DELETE {{baseURL}}/cache/forecast
Authorization: Bearer {{access_token}}
