### visitor entering park
POST {{baseURL}}/visitor/enter/{{ticketUUID}}/gate/{{$uuid}}

### visitor leaving park
POST {{baseURL}}/visitor/leave/{{ticketUUID}}/gate/{{$uuid}}

### buy a ticket valid for today
< {%
	request.variables.set("today", new Date().toISOString().slice(0, 10));
%}
POST {{baseURL}}/ticket/{{ticketUUID}}/valid-on/{{today}}

### buy a ticket valid for a specific day
POST {{baseURL}}/ticket/{{nonValidTicketId}}/valid-on/{{date}}


### enter park with not valid ticket
POST {{baseURL}}/visitor/enter/{{nonValidTicketId}}/gate/{{$uuid}}
